### ISSUE TITLE
Support for NativeScript

### ISSUE THREAD

**Issue by Ox90** [ServiceStack/servicestack-client#10]
The implementation of fetch-everywhere dont allow to run on NativeScript

**Comment by mythz** [comment]
You can submit [feature requests on UserVoice](http://servicestack.uservoice.com/forums/176786-feature-requests) so we can measure how much interest is in each feature.

**Comment by tedekeroth** [comment]
This was never implemented, I assume? I added a request =) 
https://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/33349237-support-for-servicestack-client-in-nativescript-ap

**Comment by mythz** [comment]
@servicestack/client wont be able to support NativeScript until [fetch-everywhere](https://github.com/lucasfeliciano/fetch-everywhere) adds [support for it](https://github.com/lucasfeliciano/fetch-everywhere#suported-environments) whose purpose is to provide a WHATWG `fetch` implementation across all popular JavaScript environments.

**Comment by tedekeroth** [comment]
I see, i have added an issue on that topic:
https://github.com/lucasfeliciano/fetch-everywhere/issues/10
