### ISSUE TITLE
Servicestack  client api calls & bundle minification

### ISSUE THREAD

**Issue by GeorgeKnap** [ServiceStack/servicestack-client#11]
Using `servicestack-client`'s typed api like suggested in docs
```
import { JsonServiceClient } from 'servicestack-client';
var client = new JsonServiceClient("http://gistlyn.com");
var request = new StoreGist();
const response = client.post(request);
```
will fail in production runtime if the bundle script is minified & uglified because the class names are renamed and the client will try to call API with those uglified names.

I guess it should be noted in the docs.
The easy alternative is to use plain http requests with string url.

**Comment by GeorgeKnap** [comment]
My bad. It can be dealt with the "custom url" style like in the docs.

**Comment by mythz** [comment]
BTW it should also handle support for minification as the `JsonServiceClient` will use the `getTypeName()` method for the Request DTO name when it exists, e.g:

```csharp
export class StoreGist implements IReturn<StoreGistResponse>
{
    gist: string;
    fork: boolean;
    public: boolean;
    ownerLogin: string;
    description: string;
    files: { [index:string]: GithubFile; };
    createResponse() { return new StoreGistResponse(); }
    getTypeName() { return "StoreGist"; }
}
```
