### ISSUE TITLE
Encrypted Messaging support

### ISSUE THREAD

**Issue by alinooshabadi** [ServiceStack/servicestack-client#12]
any plan to extend typed service stack client, supporting Encrypted Messaging?
like https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Client/EncryptedServiceClient.cs

**Comment by KevinHoward** [comment]
You can vote for this feature on UserVoice here
 https://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/17339578-encrypted-messaging-javascript-client

**Comment by mythz** [comment]
Right we have no plans to add it in TypeScript yet where the crypto libraries are more immature and the use of https is more prevalent. In addition to voting on the feature request @KevinHoward linked to above, please leave a comment on a specific use-case you'd like to use it for.
