### ISSUE TITLE
Production Builds Using Angular Cli with angular 5 fail

### ISSUE THREAD

**Issue by on3al** [ServiceStack/servicestack-client#13]
Performing a production build using the angular cli v 1.6.3 (angular 5.0) 
``` 
ng build --prod 

or ng serve --aot
```
Results in an error when using the
@servicestack/client 1.0.0 package

The error is:
```
ERROR in ./node_modules/@servicestack/client/src/index.ts
Module build failed: Error: {redacted}\node_modules\@servicestack\client\src\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile {redacted}\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:653:23)
    at plugin.done.then ({redacted}\\node_modules\@ngtools\webpack\src\loader.js:467:39)
 @ ./src/app/app.module.ngfactory.js 30:0-54
 @ ./src/main.ts
 @ multi ./src/main.ts
```
Project reproducing issue:
[ss-aot-issue.zip](https://github.com/ServiceStack/servicestack-client/files/1602595/ss-aot-issue.zip)
  

System information:
```
Angular CLI: 1.6.3
Node: 6.10.3
OS: win32 x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
```

**Comment by on3al** [comment]
I have also tried downgrading to Angular: 5.0.0 and the issue is still present. There are a lot of moving parts between angular, tyscript, and the cli, but I believe the issue  lies in the package. I was using this fine with angular 4, so I'm not exactly sure what changed from 4->5, but the sevice-stack cli generates angular 5.0 projects so I assume this should work.

**Comment by mythz** [comment]
Our [angular-cli](https://github.com/NetCoreTemplates/angular-cli) does work, you likely have dependency issues. Please instead create the template with:

```
$ npm install -g @servicestack/cli

$ dotnet-new angular-cli ProjectName
```

**Comment by on3al** [comment]
I generated the project, however you do not use the JsonService client anywhere in that project, it only uses the HttpClient. 
Add a provider for the JsonServiceClient in the  app.module and it will break also:

```
  providers: [JsonServiceClient],
```

**Comment by on3al** [comment]
Below is the cli client portion of the dotnet-new generated client. All I changed was to add a provider to the app-module so the JsonServiceClient gets included in the aot compilation;

[ss-aot-issu-cli-template-reproduce.zip](https://github.com/ServiceStack/servicestack-client/files/1602759/ss-aot-issu-cli-template-reproduce.zip)

to duplicate 

````
npm install
ng serve -aot
````

**Comment by mythz** [comment]
This is a result of a [recent breaking change in Angular](https://github.com/angular/angular-cli/issues/8284) which changes their module resolution. The fix ended up being to [remove index.ts from being published](https://github.com/ServiceStack/servicestack-client/commit/d5050beba0633b90044faac49d8ae3a1b02a8f07).

This change is now available from the latest [angular-cli](https://github.com/NetCoreTemplates/angular-cli) template release which is updated to use the latest Angular dependencies and includes [registration of JsonServiceClient provider](https://github.com/NetCoreTemplates/angular-cli/commit/78fa921a22e756569559d92074678a38dc4b3a84):

```ts
providers: [{provide:JsonServiceClient, useValue: new JsonServiceClient("/")}],
```

> You can't use `providers: [JsonServiceClient]` because you need to provide the baseUrl.

So this issue should now be resolved when creating a new `angular-cli` template:

    $ dotnet-new angular-cli ProjectName
