### ISSUE TITLE
Cookies not send with heartbeat request

### ISSUE THREAD

**Issue by AVee** [ServiceStack/servicestack-client#14]
Currently the Typescript ServerEventsClient does not send session cookies with the Heartbeat request. This causes issues for us because we need session information to deal with multi-tenant handling we wrote around ServerEvents on the server side.

The root cause of this seems to be that fetch() doesn't send cookies by default. We locally fixed this by added a credentials option to the fetch call on line 260:
`fetch(new Request(opt.heartbeatUrl, { method: "POST", mode: "cors", headers: headers, credentials: 'same-origin' }))`
(As per https://github.com/github/fetch#sending-cookies)

**Comment by mythz** [comment]
I've changed it to use the same credentials as the embedded ServiceClient in this commit: https://github.com/ServiceStack/servicestack-client/commit/c290e50b2f7714938374066d8426c27f6ae2f6dc

This change is available from v1.0.5 that's now on npm.

**Comment by AVee** [comment]
This works perfectly. Thanks for the quick resolution!

**Comment by AVee** [comment]
I was a to bit quick. There's another fetch in the stop() method (line 399) for the unregister call which has the same problem.
I think that is all, I can't spot any other problematic fetches.

**Comment by mythz** [comment]
np, should be resolved from this commit: https://github.com/ServiceStack/servicestack-client/commit/c729ba5d91e516bb4044558c31c0fd6d356dc72d

Available from v1.0.6 that's now published to npm.

**Comment by AVee** [comment]
Do you ever sleep? ;-) Thanks again.
