### ISSUE TITLE
How to send JWT authorization header with ServerEventsClient

### ISSUE THREAD

**Issue by hassanasad** [ServiceStack/servicestack-client#17]
I have a JWT token - I want to append it in header for the `/event-stream?channels` request. I cannot seem to find a way to do it. The only hacky way i found was to setup `new ServerEventsClient()` and then from its instance call `serviceClient.setBearerToken( token )` which does set it (as seen in console.log) but is not sent in header requests. Am i missing something very basic ?

Please help.

P.S: I am trying to implement server events in my Angular 5 app.

**Comment by mythz** [comment]
The docs contains an example of sending JWT in [both JsonServiceClient and ServerEventsClient](http://docs.servicestack.net/jwt-authprovider#send-jwts-in-http-params).

Can you please ask any support questions in the [Customer Forums](https://forums.servicestack.net/) or [StackOverflow](https://stackoverflow.com/) and reserve this issues list for reproducible bugs/issues.

**Comment by hassanasad** [comment]
Unfortunately i have tried to follow the docs you mentioned and still am blank. I have JWT token already with me. I just need to set it as "header" (Authorization: bearer {token}) for the requests being generated by ServerEventsClient. 

I have tried the `resolveStreamUrl: url => appendQueryString(url, { "ss-tok": JWT }),` method and appends the token with the URL. I need to set it in headers though.

P.S: I tried the Customer Forums and they require i have a registered email with servicestack app.

**Comment by mythz** [comment]
If you're not an active ServiceStack Customer please use StackOverflow for any future support questions.

You can't add HTTP Headers to W3C's EventSource. The docs I linked above shows the 2 options available which is to convert the JWT to a Token Cookie or enable `JwtAuthProvider.AllowInQueryString` and use `ServerEventsClient.resolveStreamUrl` to add the JWT to the event stream URL.
