### ISSUE TITLE
ServerEventsClient reconnect

### ISSUE THREAD

**Issue by GeorgeKnap** [ServiceStack/servicestack-client#8]
Hi
I suspect there may be a bug with SSE reconnect process.
The `ServerEventsClient.stop()` method sets the `ServerEventsClient.stopped` property to `true` but neither `ServerEventsClient.start()` or `ServerEventsClient.reconnectServerEvents()` switch it back to `false`.  Yes, I can assign the value manually but it does not feel right, does it? Is this a bug? 

Also, the `ServerEventsClient.reconnectServerEvents()` method contains this code:
```
if (this.stopped) return;
```
Does this mean this method is not meant to be used to reconnect stopped event source?
A little more examples at docs website would be nice as this is a bit confusing.

Cheers.
George

**Comment by mythz** [comment]
Explicitly calling `start()` should set `this.stopped=false` which was fixed in this commit: https://github.com/ServiceStack/servicestack-client/commit/6e3d818e1551d00df49982c01c9ef6eca6d969a0

This change is available from **v0.0.36** that's now available on npm.

thx for reporting!
