### ISSUE TITLE
Not found error on RequestMode and RequestCredentials types

### ISSUE THREAD

**Issue by KevinHoward** [ServiceStack/servicestack-client#9]
TypeScript is giving me a not found error on the new referenced types RequestMode and RequestCredentials from this commit 877a61e049dd04adbb81bc8ba8aee39cd6fc6b2b. 

Does a dependency to node-fetch need to be added or am I doing something wrong?

**Comment by mythz** [comment]
Are you using the latest version of TypeScript?

**Comment by KevinHoward** [comment]
Sorry.. I meant to include that.

I have the following installed.

TypeScript 2.3.4
Node 6.2.0
NPM 5.0.3

**Comment by mythz** [comment]
I didn't have npm 5 so I installed `npm install npm@latest -g`, nuked `node_modules` bumped min TypeScript version to **^2.3.4**, ran `npm install` so now versions are reporting:

```
C:\src\servicestack-client>node -v
v7.8.0

C:\src\servicestack-client>npm -v
5.0.3

C:\src\servicestack-client>tsc -v
Version 2.3.4
```

and I'm able to run `tsc` and `npm test` fine with no build errors and all tests passing. Maybe try nuking your `node_modules` and running `npm install` again?

**Comment by KevinHoward** [comment]
Will do... thanks for the help!

**Comment by mythz** [comment]
lemme know if you end up finding what the issue is as may help others who run into it.

**Comment by KevinHoward** [comment]
Looks like nuking node_modules and reloading was the trick. Not sure which module was not loading correctly to cause the issue though.
